package it.algos.vaadtest.modules.beverage;

import com.vaadin.flow.templatemodel.AllowClientUpdates;

import java.io.Serializable;

/**
 * Represents a beverage review.
 */
public class Review implements Serializable {

    private int score;

    private String name;

    private int count;

     private String inizio;

    private String fine;

    private String icona;


    /**
     * Default constructor.
     */
    public Review() {
        reset();
    }


    /**
     * Constructs a new instance with the given data.
     *
     * @param score Review score
     * @param name  Name of beverage reviewed
     * @param date  Last review date
     * @param count Times tasted
     */
    public Review(int score, String name, int count, String inizio) {
        this.score = score;
        this.name = name;
        this.count = count;
        this.inizio = inizio;
    }


    /**
     * Copy constructor.
     *
     * @param other The instance to copy
     */
    public Review(Review other) {
        this(other.getScore(), other.getName(), other.getCount(), other.getInizio());
    }


    /**
     * Resets all fields to their default values.
     */
    public void reset() {
        this.score = 1;
        this.name = "";
        this.count = 1;
    }


    /**
     * Gets the value of score
     *
     * @return the value of score
     */
    public int getScore() {
        return score;
    }


    /**
     * Sets the value of score
     *
     * @param score new value of Score
     */
    public void setScore(int score) {
        this.score = score;
    }


    /**
     * Gets the value of name
     *
     * @return the value of name
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of name
     *
     * @param name new value of name
     */
    public void setName(String name) {
        this.name = name;
    }


    /**
     * Gets the value of count
     *
     * @return the value of count
     */
    public int getCount() {
        return count;
    }


    /**
     * Sets the value of count
     *
     * @param count new value of count
     */
    public void setCount(int count) {
        this.count = count;
    }


    public String getInizio() {
        return inizio;
    }


    public void setInizio(String inizio) {
        this.inizio = inizio;
    }


    public String getFine() {
        return fine;
    }


    public void setFine(String fine) {
        this.fine = fine;
    }


    public String getIcona() {
        return icona;
    }


    public void setIcona(String icona) {
        this.icona = icona;
    }


    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Review{" + "id=" + ", score=" + getScore() + ", name="
                + getName() + ",  count=" + getCount() + ", inizio=" + getInizio()+ '}';
    }

}
